#!/usr/bin/env python3
import sys
import re
import time
import datetime
import argparse
import ballcosmos.script as bcs
import cosi.models as models
import cosi.satnogs as satnogs
import cosi.spacetrack as spacetrack


def parse_poll_interval(poll_interval: str) -> int:
    """Takes the arguments list and returns the total seconds CoSI needs to
    wait before polling spacetrack and satnogs again.

    Parameters
    ----------
    * args: `list` A python list of arguments pre-parsed by arg-parse

    Returns
    -------
    `int`: Time in seconds for CoSI to sleep

    Raises
    ------
    `ValueError`: Raises this if the user-input for `--poll-interval`
    does not match the patter `[0-9]+(d|h|m|s)`
    """
    if(re.match('[0-9]+d', poll_interval) is not None):
        timedelta = datetime.timedelta(days=int(poll_interval[:-1]))
    elif(re.match('[0-9]+h', poll_interval) is not None):
        timedelta = datetime.timedelta(hours=int(poll_interval[:-1]))
    elif(re.match('[0-9]+m', poll_interval) is not None):
        timedelta = datetime.timedelta(minutes=int(poll_interval[:-1]))
    elif(re.match('[0-9]+s', poll_interval) is not None):
        timedelta = datetime.timedelta(seconds=int(poll_interval[:-1]))
    else:
        raise ValueError('Bad poll interval value: {}.\
                        \n\tPoll interval must follow pattern: [0-9]+(d|h|m|s)\
                        \n\tEx: --poll-interval 12h or --poll-interval 30m'
                         .format(poll_interval))
    return timedelta.total_seconds()


def fetch_tle(args: list):
    tle = spacetrack.request_tle(args.norad_id)
    tle = models.TLE(header_text=tle.get('TLE_LINE0'),
                     first_line=tle.get('TLE_LINE1'),
                     second_line=tle.get('TLE_LINE2'))
    print('\n\nInserting {} into db...'.format(tle))
    models.add_tle(tle)


def fetch_telemetry(args: list):
    satellite = satnogs.request_satellite(args.norad_id)
    print('\n\nSatellite: ' + str(satellite))

    encoded_telemetry = satnogs.request_telemetry(args.norad_id)[0]
    status = {True: 'OK',
              False: 'ERR'}[encoded_telemetry != []
                            and encoded_telemetry is not None]
    print('\n\nTelemetry: ' + status)
    if(status == 'OK'):
        # Get data from DART
        packet = bcs.get_tlm_packet('ENGR_LINK', 'MAGNETOMETER')
        print('\n\nGot magentometer packets from DART: {}'.format(packet))

        # Decode telemetry
        decoded_telemetry = satnogs.decode_telemetry_frame(encoded_telemetry)

        # Get data from DART
        packet = bcs.get_tlm_packet('ENGR_LINK', 'MAGNETOMETER')
        print('\n\nGot magentometer packets from DART: {}'.format(packet))

        # Send data to dart
        magentometer_telemetry = {
            'INVALID_COUNT': decoded_telemetry.mag_invalid_count,
            'SENSOR_USED': decoded_telemetry.mag_sensor_used,
            'VECTOR_BODY1': decoded_telemetry.mag_vector_body1,
            'VECTOR_BODY2': decoded_telemetry.mag_vector_body2,
            'VECTOR_BODY3': decoded_telemetry.mag_vector_body3,
            'VECTOR_VALID': decoded_telemetry.mag_vector_valid
        }
        try:
            print('\n\nInjecting telemetry into DART: {}'
                  .format(magentometer_telemetry))
            bcs.inject_tlm('ENGR_LINK',
                           'MAGNETOMETER',
                           item_hash=magentometer_telemetry)
            print('Succesfully injected!')
        except Exception:
            print('Failed to inject telemetry frame into DART: {}'
                  .format(magentometer_telemetry))


def cycle(args):
    if(args.debug):
        print('\n\n[{}]: Starting a new poll-cycle for CoSI...'
              .format(time.ctime()))

    if(not args.no_tle):
        latest_tle = spacetrack.request_tle(args.norad_id[0])
        tle = models.TLE(header_text=latest_tle.get('TLE_LINE0'),
                         first_line=latest_tle.get('TLE_LINE1'),
                         second_line=latest_tle.get('TLE_LINE2'))
        success = models.add_tle_to_db(tle)
        if(args.debug):
            print('Latest TLE: {}\nInserted: {}'
                  .format(latest_tle, success))

    if(not args.no_satellite):
        satellite = satnogs.request_satellite(args.norad_id[0])
        if(args.debug):
            print('satellite info: {}'.format(satellite))

    if(not args.no_telemetry):
        telemetry_response = satnogs.request_telemetry(args.norad_id[0])
        if(args.debug):
            print('Telemetry: {}'.format(telemetry_response))

        frame = bytearray.fromhex(telemetry_response.get('frame'))
        decoded_telemetry = satnogs.decode_telemetry_frame(frame)
        if(args.debug):
            print('Decoded telemetry frame: {}'.format(decoded_telemetry))

    if(args.latest_tle is not None):
        try:
            norad_id = int(args.latest_tle[0])
            tle = models.get_latest_tle_by_id(norad_id)
        except ValueError:
            satellite_name = args.latest_tle[0]
            tle = models.get_latest_tle_by_name(satellite_name)
        print('Latest TLE: {}'.format(tle))


def main(args: list) -> None:
    # Parse cmd line arguments
    parser = argparse.ArgumentParser(prog='cosi-runner',
                                     description='Daemon for CoSI.',
                                     allow_abbrev=False)
    parser.add_argument('--latest-tle',
                        dest='latest_tle',
                        nargs=1,
                        metavar=('(NORAD ID|SATELLITE NAME)'),
                        help='[Default: 43793 (CSim)] Displays the latest TLE\
                              stored in DART DB either by Norad ID or by\
                              satellite name')
    parser.add_argument('-n', '--norad-id',
                        dest='norad_id',
                        nargs=1,
                        type=int,
                        default=[43793],
                        help='[Default: 43793 (CSim)] Norad Satellite ID to\
                              use when fetching TLE and Telemetry')
    parser.add_argument('--no-satellite',
                        dest='no_satellite',
                        action='store_true',
                        default=False,
                        help='Disables fetching the latest satellite info from\
                              https://db.satnogs.org')
    parser.add_argument('--no-telemetry',
                        dest='no_telemetry',
                        action='store_true',
                        default=False,
                        help='Disables fetching the latest telemetry from\
                              https://db.satnogs.org')
    parser.add_argument('--no-tle',
                        dest='no_tle',
                        action='store_true',
                        default=False,
                        help='Disables fetching the latest Two Line Element\
                             (TLE) from https://space-track.org')
    parser.add_argument('-o', '--once',
                        dest='once',
                        action='store_true',
                        default=False,
                        help='Runs a cycle once instead of looping every poll\
                        interval')
    parser.add_argument('-p', '--poll-interval',
                        dest='poll_interval',
                        nargs=1,
                        type=str,
                        default='30m',
                        help='[Default: 30m] Time interval at which CoSI polls\
                             spacetrack and satnogs for data')
    parser.add_argument('-v', '--verbose',
                        dest='debug',
                        action='store_true',
                        default=False,
                        help='Enable additional debug information')
    args = parser.parse_args(args)
    models.create_all_tables()
    poll_interval = parse_poll_interval(args.poll_interval)

    if(args.once):
        cycle(args)
    else:
        while True:
            cycle(args)
            time.sleep(poll_interval)


if __name__ == "__main__":
    main(sys.argv[1:])
