#!/bin/bash
set -e

POSTGRES="psql -d ${DART_DB} -U postgres"
$POSTGRES <<EOSQL

CREATE ROLE ${COSI_USER_NAME} WITH LOGIN ENCRYPTED PASSWORD '${COSI_PASSWORD}';
CREATE ROLE ${ULTRA_USER_NAME} WITH LOGIN ENCRYPTED PASSWORD '${ULTRA_PASSWORD}';
CREATE ROLE ${RADS_USER_NAME} WITH LOGIN ENCRYPTED PASSWORD '${RADS_PASSWORD}';

GRANT ALL ON SCHEMA public TO ${DART_USERNAME};
GRANT ALL ON SCHEMA public TO ${COSI_USER_NAME};
GRANT ALL ON SCHEMA public TO ${ULTRA_USER_NAME};
GRANT ALL ON SCHEMA public TO ${RADS_USER_NAME};

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DART_USERNAME};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${COSI_USER_NAME};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${ULTRA_USER_NAME};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${RADS_USER_NAME};

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DART_USERNAME};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${COSI_USER_NAME};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${ULTRA_USER_NAME};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${RADS_USER_NAME};

GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${DART_USERNAME};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${COSI_USER_NAME};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${ULTRA_USER_NAME};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${RADS_USER_NAME};
