#!/bin/bash
set -e

psql -d ${DART_DB} -U postgres <<EOSQL

CREATE ROLE "${DART_USERNAME}" WITH LOGIN ENCRYPTED PASSWORD '${DART_PASSWORD}';
CREATE ROLE "${COSI_USERNAME}" WITH LOGIN ENCRYPTED PASSWORD '${COSI_PASSWORD}';
CREATE ROLE "${ULTRA_USERNAME}" WITH LOGIN ENCRYPTED PASSWORD '${ULTRA_PASSWORD}';
CREATE ROLE "${RADS_USERNAME}" WITH LOGIN ENCRYPTED PASSWORD '${RADS_PASSWORD}';

GRANT ALL ON SCHEMA public TO "${DART_USERNAME}";
GRANT ALL ON SCHEMA public TO "${COSI_USERNAME}";
GRANT ALL ON SCHEMA public TO "${ULTRA_USERNAME}";
GRANT ALL ON SCHEMA public TO "${RADS_USERNAME}";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${DART_USERNAME}";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${COSI_USERNAME}";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${ULTRA_USERNAME}";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${RADS_USERNAME}";

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${DART_USERNAME}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${COSI_USERNAME}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${ULTRA_USERNAME}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${RADS_USERNAME}";

GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${DART_USERNAME}";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${COSI_USERNAME}";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${ULTRA_USERNAME}";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${RADS_USERNAME}";
EOSQL

echo -e "Done!"
